apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: default
spec:
  selector:
    app: application
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: application
    protocol: TCP
    port: 5000
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 32006
